### ISSUE TITLE
数据包在1.20和1.20.1版本中无效

### ISSUE THREAD

**Issue by Deep-Dark-Forest** [Luan-Fuzi/OldNetheriteUpgrades#1]
数据包在1.20和1.20.1版本中不起任何作用。即使加了数据包升级成下界合金也需要升级模板……我用re!看了下，结果发现也需要升级模板。

录屏：https://www.xbox.com/play/media/3EPCZV4HSB
rei截图：

**Comment by deep-dark-forest** [comment]
rei截图：
![Minecraft_ 1 20 1 2023_8_1 11_52_19](https://github.com/Luan-Fuzi/OldNetheriteUpdates/assets/131975043/44425fa6-3f7c-4f7a-b5d3-ffd99061e7c1)

**Comment by Deep-Dark-Forest** [comment]
![Minecraft_ 1 20 1 2023_8_1 11_52_19](https://github.com/Luan-Fuzi/OldNetheriteUpdates/assets/131975043/de277504-5f2d-4170-b498-547aaf7ec227)

**Comment by Luan-Fuzi** [comment]
...资源包(Resource Packs)和数据包(Datapacks)不是一个东西，将数据包拖进资源包文件夹是没有用的。请将数据包放进某个存档的/datapacks文件夹中。
